github.com:
    oauth_token: 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
    user: MrG4ming
    git_protocol: https
    users:
        MrG4ming:
            oauth_token: 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
